[4740][ADD] stock_delivery_slip_aggregate_quantity
qrtl/thc-custom pull request #13
Opened 2024-07-30 02:04 UTC by AungKoKoLin1997

[4740](https://www.quartile.co/web#id=4740&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-08-15 10:37 UTC, yostashiro requested changes

2024-08-15 10:37 UTC, yostashiro commented on stock_delivery_slip_aggregate_quantity/models/stock_move_line.py
> +            line["aggregated_move_quantity"] = aggregated_move_quantity
Update vals_list and do `create()` only once.

2024-08-15 10:37 UTC, yostashiro commented on stock_delivery_slip_aggregate_quantity/reports/report_delivery_slip.xml
> +            />
I suppose this is an oversight.
```suggestion
```

2024-08-15 10:37 UTC, yostashiro commented on stock_delivery_slip_aggregate_quantity/security/ir.model.access.csv
> +access_aggregated_move_quantity,aggregated_move_quantity,stock_delivery_slip_aggregate_quantity.model_aggregated_move_quantity,base.group_user,1,1,1,1
Please double-check if this should be how we define the ACL for this model, considering that the report may be downloaded by portal users.

2024-08-17 02:29 UTC, yostashiro approved these changes
Code review.

2024-11-14 09:04 UTC, kanda999 approved these changes
Functional review.

2024-11-14 09:04 UTC, merged